version: '3.2'
services:
  #######################################
  # Apache
  #######################################
  web:
    image: httpd
    ports:
      - "8080:80"
    volumes:
       - target:/usr/local/apache2/htdocs/ 
 
  #######################################
  # Docker SSH Sidecar
  #######################################
  sshsidecar:
    environment:
      - SSH_PASSWORD=12345
      - SSH_ROOT_PASSWORD=1234567890
    image: sebastianzoll/docker-ssh-sidecar:latest
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - target:/home/www-data
volumes:
  target: